### ISSUE TITLE
./build_dev.sh throwing errors

### ISSUE THREAD

**Issue by RBucci** [momander/wheel-spinner#59]
I'm trying to deploy a local install in ubuntu server 24.04, installed nodejs, npm, cloned the repo locally and followed the instructions in readme:

```
./build_dev.sh
rm: cannot remove 'dist/*': No such file or directory
Failed to load ./build/dev.env.
[webpack-cli] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/rholand/wheel-spinner/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/home/rholand/wheel-spinner/node_modules/webpack/lib/util/createHash.js:80:21)
    at /home/rholand/wheel-spinner/node_modules/webpack/lib/DefinePlugin.js:595:38
    at Hook.eval [as call] (eval at create (/home/rholand/wheel-spinner/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:104:1)
    at Hook.CALL_DELEGATE [as _call] (/home/rholand/wheel-spinner/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/rholand/wheel-spinner/node_modules/webpack/lib/Compiler.js:1053:26)
    at /home/rholand/wheel-spinner/node_modules/webpack/lib/Compiler.js:1097:29
    at Hook.eval [as callAsync] (eval at create (/home/rholand/wheel-spinner/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/rholand/wheel-spinner/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/rholand/wheel-spinner/node_modules/webpack/lib/Compiler.js:1092:28)
    at /home/rholand/wheel-spinner/node_modules/webpack/lib/Compiler.js:517:12
    at Compiler.readRecords (/home/rholand/wheel-spinner/node_modules/webpack/lib/Compiler.js:929:11)
    at /home/rholand/wheel-spinner/node_modules/webpack/lib/Compiler.js:514:11
    at Hook.eval [as callAsync] (eval at create (/home/rholand/wheel-spinner/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```
Can you advise?

**Comment by RealPortalPlayer** [comment]
I know this is old, but the quick solution right now is to run this:
```bash
export NODE_OPTIONS=--openssl-legacy-provider
